//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQlyRap
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public string MaKhachHang { get; set; }
        public System.DateTime NgayBan { get; set; }
        public string MaNhanVien { get; set; }
        public string MaThanhToan { get; set; }
    
        public virtual BoPhanBanVe BoPhanBanVe { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
