//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQlyRap
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public string MaThanhToan { get; set; }
        public string HinhThucThanhToan { get; set; }
        public double TongTien { get; set; }
        public System.DateTime ThoiGianThanhToan { get; set; }
        public string MaVe { get; set; }
        public string MaNhanVien { get; set; }
    
        public virtual BoPhanBanVe BoPhanBanVe { get; set; }
        public virtual Ve Ve { get; set; }
    }
}
