//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQlyRap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public string MaVe { get; set; }
        public string SoGhe { get; set; }
        public string TrangThaiVe { get; set; }
        public string MaSuatChieu { get; set; }
        public string MaKhachHang { get; set; }
        public string MaPhim { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
